#!/usr/bin/env bash
# Script install nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx reload
