#!/usr/bin/env bash
# backup and compress my databases
# Check if the password argument is provided
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi

ROOT_PASSWORD=$1
DATE="$(date +"%d-%m-%Y")"
ARCHIVE_FILE="$DATE.tar.gz"

mysqldump -u root -p"$ROOT_PASSWORD" --all-databases > backup.sql

if ! command; then
    echo "Error: MySQL dump failed."
    exit 1
fi

tar -cvzf "$ARCHIVE_FILE" backup.sql

if ! command; then
    echo "Error: Compression failed."
    exit 1
fi
#rm "backup.sql"
#echo "Backup completed: $ARCHIVE_FILE"
