#!/usr/bin/env bash
# This script ends an infinite loop statement with the command kill
pid_process=$(pgrep -f "4-to_infinity_and_beyond")
if [ -z "$pid_process" ]
then
	echo "Terminated"
else
	kill "$pid_process"
fi
