#!/usr/bin/env bash
# Configure web-01 so that its firewall redirects port 8080/TCP to port 80/TCP
sudo sed -i ""
net="#net.ipv4.ip_forward=1"

sudo sed -i "s/$net/net.ipv4.ip_forward=1/" /etc/sysctl.conf
sudo sysctl -p
sudo service ufw restart
sudo ufw enable
sudo sed -i '1i *nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT' /etc/ufw/before.rules
sudo ufw reload
