#!/usr/bin/env bash
# Bash script that listens on port 98 on localhost
# connecting to localhost on port 98 using telnet and typing some text.
# Receiving the text on the other side.

nc -l 127.0.0.1 98 &
sleep 5
telnet localhost 98
