#!/usr/bin/env bash
# This script runs the whoami command under the user passed as an argument

if [ $# -ne 1 ]; then
    echo "$0 <username>"
    exit 1
fi

username=$1

if id "$username" &>/dev/null; then
    sudo -u "$username" whoami
else
    echo "User '$username' does not exist."
    exit 1
fi
